---
name: Scheduled Secret scanning

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions: read-all

jobs:
  secret-scan:
    name: Secret scan default branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@6f3c981e7b77f235fd2702dd74af25fc4b72bf11 # v3.96.0
        with:
          path: ./
          extra_args: --results=verified,unknown
